### ISSUE TITLE
No docs on settings up .env and firebase project

### ISSUE THREAD

**Issue by macgadger** [Ctere1/react-native-chat#1]
Hi i have done all steps setting up you but unable to run the app on expo; reasone i think is not configurations and firebase 

can you please share how to setup things on firebase and link to chat app .env

**Comment by huyth-2224** [comment]
@macgadger

You can read this file https://github.com/Ctere1/react-native-chat/blob/master/.env.example

Login your firebase and get firebase info 

![firebase](https://github.com/user-attachments/assets/d863b781-cc7f-4bb5-9589-99510c56e9eb)

**Comment by Ctere1** [comment]
# Setting Up Firebase for a Chat App

## 1. Create a Firebase Project
- Go to [https://firebase.google.com/](https://firebase.google.com/) and create a new project.
- Navigate to **Authentication** and enable the Email/Password sign-in method.
- Go to **Firestore Database** and create a new database.

## 2. Get Firebase API Keys
- In your Firebase project, go to **Project Settings**.
- You’ll find your "Web API Key" and other necessary information there.

## 3. Setup .env File
- Create a `.env` file in your project and add the following:

   ```env
   #Firebase Config
   EXPO_PUBLIC_API_KEY=
   EXPO_PUBLIC_AUTH_DOMAIN=
   EXPO_PUBLIC_PROJECT_ID=
   EXPO_PUBLIC_STORAGE_BUCKET=
   EXPO_PUBLIC_MESSAGING_SENDER_ID=
   EXPO_PUBLIC_APP_ID=
   EXPO_PUBLIC_MEASUREMENT_ID=
   ```

And that's it! You should now have Firebase set up for your chat app. @macgadger
