### ISSUE TITLE
App crash after building profile APK

### ISSUE THREAD

**Issue by macgadger** [Ctere1/react-native-chat#2]
Thanks for the .env and firebase setup guide. 

I am now able to run app on ExpoGo App and all working fine there but after i build preview build .APK on eas and downloaded and installed apk on phone its crashing without any error tried clearing cache and files also.

I have Used the following to build APK
 
-  eas secret:push --scope project --env-file .env
-  eas build -p android --profile preview

Output: APK build successfully and installed on Phone 
App crashed when opening on phone no errors and nothing

**Comment by macgadger** [comment]
Runned the Logcat App via usb found that **react-native-gesture-handler** module was not installed and some other minor npm packages was outdated and fix them with expo doctor and build the APP - Working Fine on Physical Device now !

**Comment by Ctere1** [comment]
Thank you for reporting the issue. 

I will check the project to identify any problems, such as the missing `react-native-gesture-handler` module and outdated npm packages, and resolve them accordingly. 

I'll ensure the errors are fixed and the necessary dependencies are updated before building the app.
