### ISSUE TITLE
Image Attachment issues

### ISSUE THREAD

**Issue by macgadger** [Ctere1/react-native-chat#3]
When we try to send Image attachment in the chat, all Past Chat History goes blank. PFA screenshots of Before attachment screen and after attaching image.

![1](https://github.com/user-attachments/assets/8893a51e-be3b-4b40-af69-3f433de56690)
![2](https://github.com/user-attachments/assets/747f7509-0b27-4239-a6d9-6c34b1a679d1)

**Comment by Ctere1** [comment]
Hello,
Thank you for reporting the issue. I’ll take a closer look at what might be causing the chat history to disappear when sending an image attachment.

**Comment by huyth-2224** [comment]
This issue, I have fixed :D Please wait clean code and send Pull Request

**Comment by huyth-2224** [comment]
PR: https://github.com/Ctere1/react-native-chat/pull/5/files
